services:

    # services
    shapecode_iban.handler:
        class: Shapecode\Bundle\IbanBundle\Iban\IbanHandler
        public: false

    shapecode_iban.generator:
        class: Shapecode\Bundle\IbanBundle\Iban\IbanGenerator
        public: true
        arguments:
            - "@shapecode_iban.handler"
            - "%shapecode_iban.provider_name%"

    # provider
    shapecode_iban.api.iban_api_de:
        class: Shapecode\Bundle\IbanBundle\Provider\IbanApiDeProvider
        public: false
        tags:
            - { name: "shapecode_iban.provider" }

    shapecode_iban.api.open_iban:
        class: Shapecode\Bundle\IbanBundle\Provider\OpenIbanProvider
        public: false
        tags:
            - { name: "shapecode_iban.provider" }

    # commands
    shapecode_iban.command.generate_bic:
        class: Shapecode\Bundle\IbanBundle\Command\GenerateBicCommand
        arguments:
            - '@shapecode_iban.generator'
        tags:
            - { name: "console.command" }

    shapecode_iban.command.generate_iban:
        class: Shapecode\Bundle\IbanBundle\Command\GenerateIbanCommand
        arguments:
            - '@shapecode_iban.generator'
        tags:
            - { name: "console.command" }

    shapecode_iban.command.validate_iban:
        class: Shapecode\Bundle\IbanBundle\Command\ValidateIbanCommand
        arguments:
            - '@shapecode_iban.generator'
        tags:
            - { name: "console.command" }
