services:
    shapecode_iban.api.iban_api_de:
        class: Shapecode\Bundle\IbanBundle\Iban\IbanApiDeApi

    shapecode_iban.generator:
        class: Shapecode\Bundle\IbanBundle\Iban\IbanGenerator
        arguments: ["@shapecode_iban.api.iban_api_de"]
