services:

    # services
    shapecode_iban.api:
        class: Shapecode\Bundle\IbanBundle\Iban\IbanApi
        public: true

    # commands
    shapecode_iban.command.generate_iban:
        class: Shapecode\Bundle\IbanBundle\Command\GenerateIbanCommand
        arguments:
            - '@shapecode_iban.api'
        tags:
            - { name: "console.command" }

    shapecode_iban.command.validate_iban:
        class: Shapecode\Bundle\IbanBundle\Command\ValidateIbanCommand
        arguments:
            - '@shapecode_iban.api'
        tags:
            - { name: "console.command" }
